'use strict';

var gProjs = [
    {
        id: 'minesweeper',
        name: 'Minesweeper',
        title: 'Try to escape them',
        desc: 'The old famouse known game',
        url: `proj/Minesweeper/index.html`,
        publishedAt: 'June 2018',
        lables: ['Matrixes', 'Recursion'],
        img: `img/portfolio/minsweeper-tumb.png`,
        img2: `img/portfolio/minsweeper.png`,
    },
    {
        id: 'todos',
        name: 'Todos',
        title: 'Wanna do something?',
        desc: 'A simple application that will help you to manage your tsaks',
        url: `proj/Todos/index.html`,
        publishedAt: 'June 2018',
        lables: ['lable1', 'lable2'],
        img: `img/portfolio/todos-tumb.png`,
        img2: `img/portfolio/todos.png`,
    },
    {
        id: 'calculator',
        name: 'Calculator',
        title: 'Calc it...',
        desc: 'Let\'s see how good you are with numbers',
        url: `proj/calc/index.html`,
        publishedAt: 'June 2018',
        lables: ['lable1', 'lable2'],
        img: `img/portfolio/calc-tumb.png`,
        img2: `img/portfolio/calc.png`,
    },
    {
        id: 'bookshop',
        name: 'Bookshop',
        title: 'Buy it, Read it, Rate it',
        desc: 'This app is holding a vast data of books. You can add books, rate them and update their price if needed. Go and grab one...',
        url: `proj/book-shop/index.html`,
        publishedAt: 'June 2018',
        lables: ['lable1', 'lable2'],
        img: `img/portfolio/bookshop-tumb.jpg`,
        img2: `img/portfolio/bookshop.png`,
    },
    {
        id: 'touchnums',
        name: 'Touch nums',
        title: 'Touch me',
        desc: 'How fast can you click those numbers? This is a fun and enjoyable game',
        url: `proj/touch-nums/index.html`,
        publishedAt: 'June 2018',
        lables: ['lable1', 'lable2'],
        img: `img/portfolio/touch-nums-tumb.png`,
        img2: `img/portfolio/touch-nums.png`,
    },
    {
        id: 'ballboard',
        name: 'Ball board',
        title: 'Becouse balls are tasty...',
        desc: 'Like soccer? So is the green little monster in this cute funny game',
        url: `proj/ball-board/index.html`,
        publishedAt: 'June 2018',
        lables: ['lable1', 'lable2'],
        img: `img/portfolio/ball-board-tumb.png`,
        img2: `img/portfolio/ball-board.png`,
    },
    // {
    //     id: 'inpicture',
    //     name: 'In Picture',
    //     title: 'Picture perfect',
    //     desc: 'lorem ipsum lorem ipsum lorem ipsum',
    //     url: `proj/in-picture/index.html`,
    //     publishedAt: 'June 2018',
    //     lables: ['lable1', 'lable2'],
    //     img: `img/portfolio/placeholder-tumb.png`,
    //     img2: `img/portfolio/placeholder.png`,
    // },
];

